-  
    #製品名です 例:WH-USB01-THP
    DeviceName: "WS-USB01-THP"
    #各デバイスに付けた名前です
    NicName   : "replace"
    #MACアドレスです　製品裏面に記載があります
    MacAddress: "replace"
    #API叩くようのトークンです　PLANEXのサイトにログインすると確認できます
    Token     : "replace"
    #ダウンロードデータの保存先パスです
    SavePath : "replace"
    #データ取得日を現在日付から何日の形式で指定します
    #下記の例だと現在の日付から三日前のデータを一日分取得します
    From : -2
    To : -2

