-  
    #製品名です 例:WH-USB01-THP
    DeviceName: "REPLACE"
    #各デバイスに付けた名前です
    NicName   : "REPLACE"
    #MACアドレスです　製品裏面に記載があります
    MacAddress: "REPLACE"
    #API叩くようのトークンです　PLANEXのサイトにログインすると確認できます
    Token     : "REPLACE"
    #ダウンロードデータの保存先パスです
    SavePath : "REPLACE"
    #データ取得日を現在日付から何日の形式で指定します
    #下記の例だと現在の日付から三日前のデータを一日分取得します
    From : -3
    To : -3