-  
    #製品名です 例:WH-USB01-THP
    DeviceName: "WS-USB01-THP"
    #各デバイスに付けた名前です
    NicName   : "replace"
    #MACアドレスです　製品裏面に記載があります
    MacAddress: "replace"
    #API叩くようのトークンです　PLANEXのサイトにログインすると確認できます
    Token     : "replace"
    #ダウンロードデータの保存先パスです
    SavePath : "replace"
    #データ取得日を現在日付から何日の形式で指定します
    #下記の例だと現在の日付から三日前のデータを一日分取得します
    From : -2
    To : -2
<<<<<<< HEAD

-  
    #製品名です 例:WH-USB01-THP
    DeviceName: "WS-USB01-THP"
    #各デバイスに付けた名前です
    NicName   : "ISD用"
    #MACアドレスです　製品裏面に記載があります
    MacAddress: "24:72:60:31:55:6C"
    #API叩くようのトークンです　PLANEXのサイトにログインすると確認できます
    Token     : "1af32c596900fda621130dd7caecf9666"
    #ダウンロードデータの保存先パスです
    SavePath : "D:\\"
    #データ取得日を現在日付から何日の形式で指定します
    #下記の例だと現在の日付から三日前のデータを一日分取得します
    From : 0
    To : 0

-  
    #製品名です 例:WH-USB01-THP
    DeviceName: "WS-USB01-THP"
    #各デバイスに付けた名前です
    NicName   : "ASD用"
    #MACアドレスです　製品裏面に記載があります
    MacAddress: "24:72:60:40:02:4A"
    #API叩くようのトークンです　PLANEXのサイトにログインすると確認できます
    Token     : "34741a77cebb9a7c4f4318a61eb52838"
    #ダウンロードデータの保存先パスです
    SavePath : "D:\\"
    #データ取得日を現在日付から何日の形式で指定します
    #下記の例だと現在の日付から三日前のデータを一日分取得します
    From : 0
    To : 0

-  
    #製品名です 例:WH-USB01-THP
    DeviceName: "WS-USB01-THP"
    #各デバイスに付けた名前です
    NicName   : "FSD用"
    #MACアドレスです　製品裏面に記載があります
    MacAddress: "24:72:60:31:56:E4"
    #API叩くようのトークンです　PLANEXのサイトにログインすると確認できます
    Token     : "0016bd80bf3bd6a238de39831cde2444"
    #ダウンロードデータの保存先パスです
    SavePath : "D:\\"
    #データ取得日を現在日付から何日の形式で指定します
    #下記の例だと現在の日付から三日前のデータを一日分取得します
    From : 0
    To : 0

=======
>>>>>>> 973178a13cbc87cca69d577328ac657f68b4be69
